import type {GetServerSideProps} from 'next'
import Head from 'next/head'
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import {fetchTweets} from "../utils";
import {Tweet} from "../typings";
import {Toaster} from "react-hot-toast";

interface Props {
    tweets: Tweet[]
}

const Home = ({tweets}: Props) => {

  return (
      <div className={"dark:bg-black"}>
          <div className={"lg:max-w-6xl mx-auto max-h-screen overflow-hidden"}>
              <Head>
                  <title>Twitter 2.0</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <Toaster />

              <main className={"grid grid-cols-9"}>
                  <Sidebar />

                  <Feed tweets={tweets} />

                  <Widgets />
              </main>
          </div>
      </div>
  )
}

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {

    const tweets = await fetchTweets();

    return {
        props: {
            tweets,
        }
    }
};
